CURRENCY_ALIASES = {
    "доллар": "USD",
    "долларов": "USD",
    "бакс": "USD",
    "баксов": "USD",
    "долл": "USD",
    "usd": "USD",
    "$": "USD",
    "eur": "EUR",
    "евро": "EUR",
    "cny": "CNY",
    "юань": "CNY",
    "юан": "CNY",
    "inr": "INR",
    "рупия": "INR",
    "jpy": "JPY",
    "иена": "JPY",
    "aud": "AUD",
    "австралийский доллар": "AUD",
    "bgn": "BGN",
    "лев": "BGN",
    "brl": "BRL",
    "бразильский реал": "BRL",
    "cad": "CAD",
    "канадский доллар": "CAD",
    "chf": "CHF",
    "швейцарский франк": "CHF",
    "czk": "CZK",
    "чешская крона": "CZK",
    "dkk": "DKK",
    "датская крона": "DKK",
    "gbp": "GBP",
    "фунт": "GBP",
    "hkd": "HKD",
    "гонконгский доллар": "HKD",
    "huf": "HUF",
    "венгерский форинт": "HUF",
    "idr": "IDR",
    "индонезийская рупия": "IDR",
    "ils": "ILS",
    "шекель": "ILS",
    "isk": "ISK",
    "исландская крона": "ISK",
    "krw": "KRW",
    "вон": "KRW",
    "mxn": "MXN",
    "мексиканское песо": "MXN",
    "myr": "MYR",
    "малайзийский ринггит": "MYR",
    "nok": "NOK",
    "норвежская крона": "NOK",
    "nzd": "NZD",
    "новозеландский доллар": "NZD",
    "php": "PHP",
    "филиппинское песо": "PHP",
    "pln": "PLN",
    "злотый": "PLN",
    "ron": "RON",
    "лей": "RON",
    "sek": "SEK",
    "шведская крона": "SEK",
    "sgd": "SGD",
    "сингапурский доллар": "SGD",
    "thb": "THB",
    "бат": "THB",
    "try": "TRY",
    "турецкая лира": "TRY",
    "zar": "ZAR",
    "ранд": "ZAR"
}

TARGET_CURRENCIES = ["USD", "EUR", "CNY", "INR", "JPY",   "AUD", "BGN", "BRL", "CAD", "CHF", "CZK", "DKK", "GBP", "HKD", "HUF", "IDR", "ILS", "ISK", "KRW", "MXN", "MYR", "NOK", "NZD", "PHP", "PLN", "RON", "SEK", "SGD", "THB", "TRY", "ZAR"]